# Generated by Django 6.0.2 on 2026-05-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barras',
        ),
    ]
