# Generated by Django 6.0.2 on 2026-05-03 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gestion_finanzas.tipogasto')),
            ],
        ),
    ]
