# Generated by Django 6.0.2 on 2026-05-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('productos', 'Productos'), ('gastos', 'Gastos'), ('usuarios', 'Usuarios'), ('ventas', 'Ventas'), ('detalle_ventas', 'Detalle de Ventas')], default='productos', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_generacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
